# Generated by Django 6.0.8 on 2026-08-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='yearly_case_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Extra cases granted on top of max_cases when the organization is billed YEARLY for this plan (reward for committing annually). Ignored when max_cases is 0 (unlimited). E.g. max_cases=25, yearly_case_bonus=10 -> yearly subscribers get 35 cases.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_cases',
            field=models.PositiveIntegerField(default=3, help_text='Active cases per organization on MONTHLY billing. 0 = unlimited.'),
        ),
    ]
