# Generated by Django 6.0.7 on 2026-07-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('examiner', 'Forensic Examiner'), ('viewer', 'Read-only Reviewer')], default='examiner', max_length=16)),
                ('organization', models.CharField(blank=True, default='Agamya Cyber Tech', max_length=150)),
                ('badge_id', models.CharField(blank=True, help_text='Examiner / badge / employee ID', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
