# Generated by Django 6.0.7 on 2026-07-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('chromium_history', 'Chromium History (Chrome/Edge/Brave/Opera)'), ('chromium_logins', 'Chromium Login Data'), ('chromium_cookies', 'Chromium Cookies'), ('chromium_downloads', 'Chromium Downloads (from History DB)'), ('firefox_history', 'Firefox places.sqlite'), ('firefox_logins', 'Firefox logins.json'), ('firefox_cookies', 'Firefox cookies.sqlite'), ('safari_history', 'Safari History.db'), ('cache_archive', 'Cache folder (.zip, metadata only)'), ('other', 'Other / unclassified')], max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Parse failed')], default='uploaded', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('source_browser_hint', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_path', models.TextField(blank=True)),
                ('source_url', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('danger_type', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_entries', to='evidence.evidenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='CookieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('is_httponly', models.BooleanField(default=False)),
                ('last_access_utc', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(default='Protected', max_length=50)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_entries', to='evidence.evidenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('path', models.TextField(blank=True)),
                ('mime_guess', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='evidence.evidenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='LoginEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('username', models.CharField(blank=True, max_length=300)),
                ('password_value', models.CharField(default='Protected', max_length=50)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_entries', to='evidence.evidenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('visit_count', models.IntegerField(default=0)),
                ('last_visit_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='evidence.evidenceitem')),
            ],
            options={
                'indexes': [models.Index(fields=['evidence', 'last_visit_time'], name='evidence_hi_evidenc_8f1789_idx')],
            },
        ),
    ]
